# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='组名')),
            ],
            options={
                'db_table': 't_group',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='权限名称')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='访问路径')),
                ('method', models.CharField(blank=True, choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete')], max_length=16, null=True, verbose_name='请求方法')),
                ('parameter', models.CharField(blank=True, max_length=255, null=True, verbose_name='请求参数')),
            ],
            options={
                'db_table': 't_permission',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='令牌')),
            ],
            options={
                'db_table': 't_token',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('group', models.ManyToManyField(to='user.Group', verbose_name='组名')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='group',
            name='permission',
            field=models.ManyToManyField(to='user.Permission', verbose_name='可访问路径'),
        ),
    ]
