# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_token_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='update_time',
            field=models.TimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
