# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180627_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
